###
### 22.08.2019 split up
###

name: Einstellungen
view: yes
entities:
    - group.automation_rules
    - group.automation_hidden_entities
    - group.automation_pixel_node_preferences
    - group.automation_light_simulation
    - group.automation_pool
    - group.automation_ws2812
