###
### junand 23.09.2016
###

# -------------------------------------------------------------------------------

homeassistant:

  # Name of the location where Home Assistant is running
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude

  # Impacts weather/sunrise data
  elevation: 59

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize: !include conf/customize.yaml

system_health:

# -------------------------------------------------------------------------------
# logger

logger:
  # default: debug
  # default: info
  default: warn
  logs:
    homeassistant.components.automation: debug
    # boschshcpy: debug

# -------------------------------------------------------------------------------
# mqtt broker

mqtt:
  broker: mosquitto
  port: 1883
  client_id: home_assistant
  keepalive: 120
  protocol: 3.1.1

# -------------------------------------------------------------------------------
# influxdb
# https://home-assistant.io/blog/2015/12/07/influxdb-and-grafana/

influxdb:
  api_version: 2
  ssl: false
  host: influxdb
  port: 8086
  token: !secret influxdb_token
  organization: !secret influxdb_organization
  bucket: home_assistant
  include:
    entities:
        - sensor.dht22_terrace_temperature
        - sensor.dht22_roof_temperature
        - sensor.dht22_lounge_temperature
        - sensor.relay_garage_temperature
        - sensor.dht22_office_temperature
        - sensor.dht22_terrace_humidity
        - sensor.dht22_roof_humidity
        - sensor.dht22_lounge_humidity
        - sensor.relay_garage_humidity
        - sensor.dht22_office_humidity
        - sensor.DHT22_lounge_pressure
        - sensor.ds18b20_pool_temperature
        - sensor.ds18b20_pool_voltage
        - sensor.soil_garden_temperature1
        - sensor.soil_garden_temperature2
        - sensor.soil_garden_temperature3
        - sensor.soil_garden_moisture1
        - sensor.soil_garden_moisture2
        - sensor.soil_garden_moisture3
        - sensor.rain_garden_precipitation
        - sensor.goldfruchtpalme_flowercare_battery
        - sensor.goldfruchtpalme_flowercare_moisture
        - sensor.goldfruchtpalme_flowercare_temperature
        - sensor.goldfruchtpalme_flowercare_conductivity
        - sensor.goldfruchtpalme_flowercare_brightness
        - sensor.birkenfeige_flowercare_battery
        - sensor.birkenfeige_flowercare_moisture
        - sensor.birkenfeige_flowercare_temperature
        - sensor.birkenfeige_flowercare_conductivity
        - sensor.birkenfeige_flowercare_brightness
        - sensor.palmlilie_flowercare_battery
        - sensor.palmlilie_flowercare_moisture
        - sensor.palmlilie_flowercare_temperature
        - sensor.palmlilie_flowercare_conductivity
        - sensor.palmlilie_flowercare_brightness
        - sensor.bogenhanf_flowercare_battery
        - sensor.bogenhanf_flowercare_moisture
        - sensor.bogenhanf_flowercare_temperature
        - sensor.bogenhanf_flowercare_conductivity
        - sensor.bogenhanf_flowercare_brightness
        - sensor.korbmarante_flowercare_battery
        - sensor.korbmarante_flowercare_moisture
        - sensor.korbmarante_flowercare_temperature
        - sensor.korbmarante_flowercare_conductivity
        - sensor.korbmarante_flowercare_brightness
        - sensor.fensterblatt_flowercare_battery
        - sensor.fensterblatt_flowercare_moisture
        - sensor.fensterblatt_flowercare_temperature
        - sensor.fensterblatt_flowercare_conductivity
        - sensor.fensterblatt_flowercare_brightness
        - sensor.gummibaum_flowercare_battery
        - sensor.gummibaum_flowercare_moisture
        - sensor.gummibaum_flowercare_temperature
        - sensor.gummibaum_flowercare_conductivity
        - sensor.gummibaum_flowercare_brightness
        - sensor.plant8_flowercare_battery
        - sensor.plant8_flowercare_moisture
        - sensor.plant8_flowercare_temperature
        - sensor.plant8_flowercare_conductivity
        - sensor.plant8_flowercare_brightness
  ignore_attributes:
    - friendly_name
    - icon
    - last_period
    - last_reset
    - meter_period
    - source
    - status

# -------------------------------------------------------------------------------
# define all zones explicite and manual
# pictures from https://materialdesignicons.com/

zone: !include conf/zone.yaml

# -------------------------------------------------------------------------------
# Show links to resources in log and frontend
###introduction:

# -------------------------------------------------------------------------------
# Enables the frontend
frontend:

lovelace:
    mode: yaml
    resources:
      # https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card
      - url: /local/custom_lovelace/xiaomi_vacuum_map_card/xiaomi-vacuum-map-card.js
        type: module
      # # https://github.com/custom-cards/vertical-stack-in-card
      # - url: /local/vertical-stack-in-card.js
        # type: js
    dashboards:
        settings-dashboard:
            mode: yaml
            filename: ui-settings.yaml
            title: Einstellungen
            icon: mdi:cog
            show_in_sidebar: true
            require_admin: false
        system-dashboard:
            mode: yaml
            filename: ui-system.yaml
            title: System
            icon: mdi:memory
            show_in_sidebar: true
            require_admin: false
        values-dashboard:
            mode: yaml
            filename: ui-values.yaml
            title: Sensorwerte
            icon: mdi:chart-line
            show_in_sidebar: true
            require_admin: false
        brewery-dashboard:
            mode: yaml
            filename: ui-brewery.yaml
            title: Brauerei
            icon: mdi:beer
            show_in_sidebar: true
            require_admin: false
        old-dashboard:
            mode: yaml
            filename: ui-old.yaml
            title: Old Dashboard
            show_in_sidebar: false
            require_admin: false

# -------------------------------------------------------------------------------
http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # from https://community.home-assistant.io/t/reverse-proxy-error/312936/18
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/8

# -------------------------------------------------------------------------------
# Checks for available updates
updater:

# -------------------------------------------------------------------------------
# Discover some devices automatically
###discovery:

# -------------------------------------------------------------------------------
# Allows you to issue voice commands from the frontend in enabled browsers
###conversation:

# -------------------------------------------------------------------------------
# Enables the recorder component.
recorder:
    auto_purge: on
    purge_keep_days: 30

# -------------------------------------------------------------------------------
# Enables support for tracking state changes over time.
history:
    include:
        domains:
            - sensor
            - light
            - switch
            - cover
            - media_player
            - device_tracker
        # entities:

# -------------------------------------------------------------------------------
# Enables support for logbook component.
logbook:
    include:
        domains:
            - sensor
            - light
            - switch
            - cover
            - media_player
            - device_tracker
        # entities:
        
# -------------------------------------------------------------------------------
# hostname
input_text:
  hostname:
    initial: !env_var PARENT_HOSTNAME

# -------------------------------------------------------------------------------
# Track the sun
sun:

# -------------------------------------------------------------------------------
# camera for roborock map
# https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor
# https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card
camera:
  - platform: xiaomi_cloud_map_extractor
    name: "Roborock S6 ground floor"
    host: 192.168.2.129
    token: !secret token_vacuum_ground_floor
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    # country: de
    draw: ['all']
    attributes:
      - calibration_points
      - country
      - rooms
      - zones
  - platform: xiaomi_cloud_map_extractor
    name: "Roborock S6 first floor"
    host: 192.168.2.151
    token: !secret token_vacuum_first_floor
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    # country: de
    draw: ['all']
    attributes:
      - calibration_points
      - country
      - rooms
      - zones

# -------------------------------------------------------------------------------
#
sensor:         !include_dir_merge_list     conf/sensor
binary_sensor:  !include_dir_merge_list     conf/binary_sensor
light:          !include_dir_merge_list     conf/light
switch:         !include_dir_merge_list     conf/switch
cover:          !include_dir_merge_list     conf/cover
group:          !include_dir_named          conf/group
input_boolean:  !include_dir_merge_named    conf/input_boolean
input_number:   !include_dir_named          conf/input_number
input_select:   !include_dir_named          conf/input_select
input_datetime: !include_dir_named          conf/input_datetime
scene:          !include                    conf/scene.yaml
automation:     !include_dir_merge_list     conf/automation
counter:        !include_dir_named          conf/counter
plant:          !include_dir_named          conf/plant

# -------------------------------------------------------------------------------
#
# deprecated integrations
#
# -------------------------------------------------------------------------------
# weather platform for lovelace card

# weather:
  # - platform: openweathermap
    # api_key: !secret api_key_openweather

# -------------------------------------------------------------------------------
# roborock s6
# vacuum:
  # - platform: xiaomi_miio
    # name: "Roborock S6 ground floor"
    # host: 192.168.2.129
    # token: !secret token_vacuum_ground_floor
  # - platform: xiaomi_miio
    # name: "Roborock S6 first floor"
    # host: 192.168.2.151
    # token: !secret token_vacuum_first_floor

# -------------------------------------------------------------------------------
# tracker

# device_tracker:

  # - platform: fritz
    # host: 192.168.2.1
    # consider_home: 180
    # interval_seconds: 60
    # track_new_devices: true

  # - platform: owntracks
    # max_gps_accuracy: 1500
    # waypoints: False

# -------------------------------------------------------------------------------
# media player

# media_player:
  # - platform: braviatv
    # host: 192.168.2.116

# -------------------------------------------------------------------------------
# Bosch Smart Home
# https://github.com/tschamm/boschshc-hass
# bosch_shc:
   # ip_address: '192.168.2.155'
   # ssl_certificate: '/config/custom_components/bsh-client-cert.pem'
   # ssl_key: '/config/custom_components/bsh-client-key.pem'
   # name: 'SHC-Controller'
