###
### junand 23.09.2016
###

# -------------------------------------------------------------------------------

homeassistant:

  # Name of the location where Home Assistant is running
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude

  # Impacts weather/sunrise data
  elevation: 59

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize: !include conf/customize.yaml

system_health:

# -------------------------------------------------------------------------------
# mqtt broker

mqtt:
  broker: mosquitto
  port: 1883
  client_id: home_assistant
  keepalive: 120
  protocol: 3.1.1

# -------------------------------------------------------------------------------
# influxdb
# https://home-assistant.io/blog/2015/12/07/influxdb-and-grafana/

influxdb:
  host: influxdb
  port: 8086
  database: home_assistant
  username: ha
  password: ha
  include:
    entities:
        - sensor.DHT22_terrace_temperature
        - sensor.DHT22_roof_temperature
        - sensor.DHT22_lounge_temperature
        - sensor.relay_garage_temperature
        - sensor.DHT22_terrace_humidity
        - sensor.DHT22_roof_humidity
        - sensor.DHT22_lounge_humidity
        - sensor.relay_garage_humidity
        - sensor.DHT22_lounge_pressure
        - sensor.ds18b20_pool_temperature
        - sensor.ds18b20_pool_voltage

# -------------------------------------------------------------------------------
# weather platform for lovelace card

weather:
  - platform: openweathermap
    api_key: !secret api_key_openweather

# -------------------------------------------------------------------------------
# media player

media_player:
  - platform: braviatv
    host: 192.168.2.116

# -------------------------------------------------------------------------------
# tracker

device_tracker:

  - platform: fritz
    host: 192.168.2.1
    consider_home: 180
    interval_seconds: 60
    track_new_devices: false

  # - platform: owntracks
    # max_gps_accuracy: 1500
    # waypoints: False

#------------------------------------------------------------------------------
# speedtest
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

# -------------------------------------------------------------------------------
# define all zones explicite and manual
# pictures from https://materialdesignicons.com/

zone: !include conf/zone.yaml

# -------------------------------------------------------------------------------
# Show links to resources in log and frontend
###introduction:

# -------------------------------------------------------------------------------
# Enables the frontend
frontend:

lovelace:
    mode: yaml

# -------------------------------------------------------------------------------
http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# -------------------------------------------------------------------------------
# Checks for available updates
updater:
    include_used_components: true

# -------------------------------------------------------------------------------
# Discover some devices automatically
###discovery:

# -------------------------------------------------------------------------------
# Allows you to issue voice commands from the frontend in enabled browsers
###conversation:

# -------------------------------------------------------------------------------
# Enables the recorder component.
recorder:
    auto_purge: on
    purge_keep_days: 30

# -------------------------------------------------------------------------------
# Enables support for tracking state changes over time.
history:
    include:
        domains:
            - sensor
            - light
            - switch
            - cover
            - media_player
            - device_tracker
        # entities:

# -------------------------------------------------------------------------------
# Enables support for logbook component.
logbook:
    include:
        domains:
            - sensor
            - light
            - switch
            - cover
            - media_player
            - device_tracker
        # entities:
        
# -------------------------------------------------------------------------------
# hostname
input_text:
  hostname:
    initial: !env_var PARENT_HOSTNAME

# -------------------------------------------------------------------------------
# roborock s6
vacuum:
  - platform: xiaomi_miio
    name: "Roborock S6 ground floor"
    host: 192.168.2.129
    token: !secret token_vacuum_ground_floor
  - platform: xiaomi_miio
    name: "Roborock S6 first floor"
    host: 192.168.2.151
    token: !secret token_vacuum_first_floor

# -------------------------------------------------------------------------------
# Track the sun
sun:

# -------------------------------------------------------------------------------
#
sensor:         !include_dir_merge_list     conf/sensor
binary_sensor:  !include_dir_merge_list     conf/binary_sensor
light:          !include_dir_merge_list     conf/light
switch:         !include_dir_merge_list     conf/switch
cover:          !include_dir_merge_list     conf/cover
group:          !include_dir_named          conf/group
input_boolean:  !include_dir_merge_named    conf/input_boolean
scene:          !include                    conf/scene.yaml
input_number:   !include_dir_named          conf/input_number
automation:     !include_dir_merge_list     conf/automation
input_select:   !include_dir_named          conf/input_select

# -------------------------------------------------------------------------------
