###
### junand 23.09.2016
###

# -------------------------------------------------------------------------------

homeassistant:

  # Name of the location where Home Assistant is running
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude

  # Impacts weather/sunrise data
  elevation: 59

  # metric for Metric, imperial for Imperial
  unit_system: metric

  currency: EUR

  country: DE

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize: !include conf/customize.yaml

system_health:

# -------------------------------------------------------------------------------
# logger

logger:
  # default: debug
  # default: info
  default: warn
  #logs:
    # homeassistant.components.automation: debug
    #boschshcpy: debug
    #custom_components.bosch_shc: debug
    # custom_components.becker: debug
    # custom_component.solarman: debug
    # homeassistant.helper.update: debug
    # custom_components.innova: debug

# -------------------------------------------------------------------------------
# shell commands

shell_command:
    request_shutdown: cat shutdown > /var/tmp/shutdown_signal

# -------------------------------------------------------------------------------
# influxdb
# https://home-assistant.io/blog/2015/12/07/influxdb-and-grafana/

influxdb: !include conf/influxdb.yaml

# -------------------------------------------------------------------------------
# define all zones explicite and manual
# pictures from https://materialdesignicons.com/

zone: !include conf/zone.yaml

# -------------------------------------------------------------------------------
# Show links to resources in log and frontend
###introduction:

# -------------------------------------------------------------------------------
# Enables the frontend
frontend:
    themes: !include_dir_merge_named conf/themes

lovelace:
    mode: yaml
    resources:
      # https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card
      - url: /local/custom_lovelace/xiaomi_vacuum_map_card/xiaomi-vacuum-map-card.js
        type: module
      # https://github.com/thomasloven/lovelace-card-mod
      - url: /local/custom_lovelace/lovelace-card-mod/card-mod.js
        type: module
      # https://github.com/ExperienceLovelace/ha-floorplan
      - url: /local/custom_lovelace/ha-floorplan/floorplan.js
        type: module
      # https://github.com/Madelena/Metrology-for-Hass
      - url: /local/themes/styles.css
        type: css
      # https://github.com/thomasloven/lovelace-state-switch
      - url: /local/custom_lovelace/lovelace-state-switch/state-switch.js
        type: module
    dashboards:
        values-dashboard:
            mode: yaml
            filename: ui-values.yaml
            title: Sensorwerte
            icon: mdi:chart-line
            show_in_sidebar: true
            require_admin: false
        settings-dashboard:
            mode: yaml
            filename: ui-settings.yaml
            title: Einstellungen
            icon: mdi:cog
            show_in_sidebar: true
            require_admin: false
        system-dashboard:
            mode: yaml
            filename: ui-system.yaml
            title: System
            icon: mdi:memory
            show_in_sidebar: true
            require_admin: false
        brewery-dashboard:
            mode: yaml
            filename: ui-brewery.yaml
            title: Brauerei
            icon: mdi:beer
            show_in_sidebar: false
            require_admin: false
        old-dashboard:
            mode: yaml
            filename: ui-old.yaml
            title: Old Dashboard
            show_in_sidebar: false
            require_admin: false

# -------------------------------------------------------------------------------
http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # from https://community.home-assistant.io/t/reverse-proxy-error/312936/18
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/8

# -------------------------------------------------------------------------------
# Discover some devices automatically
###discovery:

# -------------------------------------------------------------------------------
# Allows you to issue voice commands from the frontend in enabled browsers
###conversation:

# -------------------------------------------------------------------------------
# Enables the recorder component.
recorder:
    auto_purge: on
    purge_keep_days: 30
    auto_repack: true

# -------------------------------------------------------------------------------
# Enables support for tracking state changes over time.
history:

# -------------------------------------------------------------------------------
# Enables support for logbook component.
# By default, the logbook will use the same filter as the recorder.
logbook:

# -------------------------------------------------------------------------------
# hostname
input_text:
    hostname:
        initial: !env_var PARENT_HOSTNAME

# -------------------------------------------------------------------------------
# Track the sun
sun:

# -------------------------------------------------------------------------------
# energy panel
energy:

# -------------------------------------------------------------------------------
# camera for roborock map
# https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor
# https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card
# camera:
  # - platform: xiaomi_cloud_map_extractor
    # name: "Roborock S6 ground floor"
    # host: 192.168.2.129
    # token: !secret token_vacuum_ground_floor
    # username: !secret xiaomi_cloud_username
    # password: !secret xiaomi_cloud_password
    # # country: de
    # draw: ['all']
    # attributes:
      # - calibration_points
      # - country
      # - rooms
      # - zones
  # - platform: xiaomi_cloud_map_extractor
    # name: "Roborock S6 first floor"
    # host: 192.168.2.151
    # token: !secret token_vacuum_first_floor
    # username: !secret xiaomi_cloud_username
    # password: !secret xiaomi_cloud_password
    # # country: de
    # draw: ['all']
    # attributes:
      # - calibration_points
      # - country
      # - rooms
      # - zones

# -------------------------------------------------------------------------------
#
template:           !include_dir_merge_list     conf/template
sensor:             !include_dir_merge_list     conf/sensor
binary_sensor:      !include_dir_merge_list     conf/binary_sensor
light:              !include_dir_merge_list     conf/light
switch:             !include_dir_merge_list     conf/switch
cover:              !include_dir_merge_list     conf/cover
group:              !include_dir_named          conf/group
input_boolean:      !include_dir_merge_named    conf/input_boolean
input_number:       !include_dir_named          conf/input_number
input_select:       !include_dir_named          conf/input_select
input_datetime:     !include_dir_named          conf/input_datetime
scene:              !include                    conf/scene.yaml
automation:         !include_dir_merge_list     conf/automation
script:             !include_dir_merge_list     conf/script
counter:            !include_dir_named          conf/counter
plant:              !include_dir_named          conf/plant
mqtt:
    light:          !include_dir_merge_list     conf/mqtt_light
    binary_sensor:  !include_dir_merge_list     conf/mqtt_binary_sensor
    sensor:         !include_dir_merge_list     conf/mqtt_sensor
    switch:         !include_dir_merge_list     conf/mqtt_switch
    cover:          !include_dir_merge_list     conf/mqtt_cover
utility_meter:      !include_dir_named          conf/utility_meter
modbus:             !include_dir_merge_list     conf/modbus
command_line:       !include_dir_merge_list     conf/command_line
input_button:       !include_dir_named          conf/input_button

# -------------------------------------------------------------------------------
#
# deprecated integrations
#
# -------------------------------------------------------------------------------
# weather platform for lovelace card

# weather:
  # - platform: openweathermap
    # api_key: !secret api_key_openweather

# -------------------------------------------------------------------------------
# roborock s6
# vacuum:
  # - platform: xiaomi_miio
    # name: "Roborock S6 ground floor"
    # host: 192.168.2.129
    # token: !secret token_vacuum_ground_floor
  # - platform: xiaomi_miio
    # name: "Roborock S6 first floor"
    # host: 192.168.2.151
    # token: !secret token_vacuum_first_floor

# -------------------------------------------------------------------------------
# tracker

# device_tracker:

  # - platform: fritz
    # host: 192.168.2.1
    # consider_home: 180
    # interval_seconds: 60
    # track_new_devices: true

  # - platform: owntracks
    # max_gps_accuracy: 1500
    # waypoints: False

# -------------------------------------------------------------------------------
# media player

# media_player:
  # - platform: braviatv
    # host: 192.168.2.116

# -------------------------------------------------------------------------------
# Bosch Smart Home
# https://github.com/tschamm/boschshc-hass
# bosch_shc:
   # ip_address: '192.168.2.155'
   # ssl_certificate: '/config/custom_components/bsh-client-cert.pem'
   # ssl_key: '/config/custom_components/bsh-client-key.pem'
   # name: 'SHC-Controller'

# -------------------------------------------------------------------------------
# mqtt broker

# mqtt:
  # broker: mosquitto
  # port: 1883
  # client_id: home_assistant
  # keepalive: 120
  # protocol: 3.1.1
