###
### junand 23.09.2016
###

# -------------------------------------------------------------------------------

homeassistant:

  # Name of the location where Home Assistant is running
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude

  # Impacts weather/sunrise data
  elevation: 59

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize: !include conf/customize.yaml

# -------------------------------------------------------------------------------
# mqtt broker

mqtt:
  broker: localhost
  port: 1883
  client_id: home_assistant_prod
  keepalive: 120
  protocol: 3.1.1

# -------------------------------------------------------------------------------
# influxdb
# https://home-assistant.io/blog/2015/12/07/influxdb-and-grafana/

influxdb:
  host: localhost
  port: 8086
  database: home_assistant
  username: ha
  password: ha
  include:
    entities:
        - sensor.DHT11terrace_temperature
        - sensor.DHT11roof_temperature
        - sensor.DHT11lounge_temperature
        - sensor.relaygarage_temperature
        - sensor.DHT11terrace_humidity
        - sensor.DHT11roof_humidity
        - sensor.DHT11lounge_humidity
        - sensor.relaygarage_humidity
        - sensor.DHT11lounge_pressure
        - sensor.ds18b20pool_temperature
        - sensor.ds18b20pool_voltage_original
        - sensor.oledkitchen_voltage_original

# -------------------------------------------------------------------------------
# weblinks

weblink:
  entities:
    - name: Home Assistant
      url: https://home-assistant.io
    - name: OctoPrint
      url: http://192.168.2.114
      icon: mdi:printer-3d

# -------------------------------------------------------------------------------
# media player

media_player:
  - platform: braviatv
    host: 192.168.2.104

# -------------------------------------------------------------------------------
# octoprint:
  # host: 192.168.2.114
  # api_key: !secret api_key_octoprint

# -------------------------------------------------------------------------------
# tracker

device_tracker:

  - platform: fritz
    host: 192.168.2.1

  # - platform: owntracks
    # max_gps_accuracy: 1500
    # waypoints: False

# -------------------------------------------------------------------------------
# define all zones explicite and manual
# pictures from https://materialdesignicons.com/

zone: !include conf/zone.yaml

# -------------------------------------------------------------------------------
# Show links to resources in log and frontend
###introduction:

# -------------------------------------------------------------------------------
# Enables the frontend
frontend:

# -------------------------------------------------------------------------------
http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# -------------------------------------------------------------------------------
# Checks for available updates
updater:
    include_used_components: true

# -------------------------------------------------------------------------------
# Discover some devices automatically
###discovery:

# -------------------------------------------------------------------------------
# Allows you to issue voice commands from the frontend in enabled browsers
###conversation:

# -------------------------------------------------------------------------------
# Enables support for tracking state changes over time.
history:
    include:
        domains:
            - sensor
            - light
            - switch
            - cover
        # entities:
        
# -------------------------------------------------------------------------------
# View all events in a logbook
#logbook:

# -------------------------------------------------------------------------------
# Track the sun
sun:

# -------------------------------------------------------------------------------
#
sensor: !include conf/sensor.yaml

# -------------------------------------------------------------------------------
#
binary_sensor: !include conf/binary_sensor.yaml

# -------------------------------------------------------------------------------
#
light: !include conf/light.yaml

# -------------------------------------------------------------------------------
#
switch: !include conf/switch.yaml

# -------------------------------------------------------------------------------
#
cover:
  - platform: mqtt
    name: "relay@garage"
    state_topic: nodes@home/cover/relay/garage/value/position
    command_topic: nodes@home/cover/relay/garage/command
    state_open: "open"
    state_closed: "closed"
    retain: false
    optimistic: false

# -------------------------------------------------------------------------------
#
group: !include conf/group.yaml

# -------------------------------------------------------------------------------
#
input_boolean: !include conf/input_boolean.yaml

# -------------------------------------------------------------------------------
#
scene: !include conf/scene.yaml

# -------------------------------------------------------------------------------
#
input_slider:
    pixel_node_display_duration:
        name: Anzeigedauer
        initial: 5
        min: 1
        max: 10
        step: 1
    pixel_node_display_brightness:
        name: Anzeigehelligkeit
        initial: 0
        min: 0
        max: 15
        step: 1

# -------------------------------------------------------------------------------
#
automation: !include conf/automation.yaml

# -------------------------------------------------------------------------------
