#
# lovelace configuration - one big file for all
#

title: !env_var HA_TITLE
views:

  - title: Lichter
    path: lights
    panel: false
    cards:
      - type: entities
        title: Abwesenheit
        show_header_toggle: false
        entities:
            - input_boolean.light_simulation
            - input_number.max_random_off_duration
      - type: entities
        title: Zeiten
        entities:
            - input_datetime.standup_workday
            - input_datetime.standup_weekend
            - input_datetime.sleep
            - input_number.light_timeout
            - input_boolean.light_delay_bath
            - input_boolean.light_delay_shower
      - type: entities
        title: Fernseher aus
        entities:
            - input_number.tvoff_lightsoff_delay1
            - input_number.tvoff_lightsoff_delay2
            - input_datetime.tv_off_period_start
            - input_datetime.tv_off_period_end
      - type: entities
        title: Nachtlicht
        entities:
            - input_number.nightlight_duration
            - input_datetime.nightlight_end
      - type: vertical-stack
        cards:
          - type: entities
            title: PiTouch
            entities:
                - input_number.pitouch_delay
                - input_datetime.pitouch_off
                - input_select.pitouch_temp_display
      - type: vertical-stack
        cards:
          - type: entities
            title: Lichterkette
            show_header_toggle: false
            entities:
                - input_number.effect_delay

  - title: Garten
    path: garden
    panel: false
    cards:
      - type: entities
        title: Gartenbewässerung
        show_header_toggle: false
        entities:
            - input_number.irrigation_duration
            - input_boolean.irrigation_activated
            - input_datetime.irrigation_start1
            - input_select.irrigation_day1
            - input_select.irrigation_day2
            - input_select.irrigation_day3
            - input_number.irrigation_rain_threshold
            - input_number.irrigation_no_rain_days_threshold
            - input_number.irrigation_temperature_threshold
            - input_number.irrigation_warm_days_threshold
      - type: entities
        title: Pool
        show_header_toggle: false
        entities:
            - input_number.pool_pump_duration
            - input_datetime.pool_pump_start1
            - input_datetime.pool_pump_start2

  - title: Schalter
    path: buttons
    panel: false
    cards:
      - type: entities
        title: Drücker
        show_header_toggle: true
        entities:
            - input_boolean.button_indoor_activated
            - binary_sensor.button_indoor
            - input_boolean.button_garage_activated
            - binary_sensor.button_garage
            - input_boolean.button_pool_activated
            - binary_sensor.button_pool
            - input_boolean.gesture_kitchen_activated
            - binary_sensor.gesture_kitchen
            - input_boolean.touch_bedroom_activated
            - binary_sensor.ttp223_bedroom_touch1
            - binary_sensor.ttp223_bedroom_touch2
            - binary_sensor.ttp223_bedroom_touch3
            - binary_sensor.ttp223_bedroom_touch4

  - title: Pixel Node
    path: pixelnode
    panel: false
    cards:
      - type: entities
        title: Datum und Zeit
        show_header_toggle: false
        entities:
            - input_boolean.pixel_node_time
            - input_boolean.pixel_node_date
            - input_boolean.pixel_node_weekday
      - type: entities
        title: Anzeige
        show_header_toggle: false
        entities:
            - input_number.pixel_node_display_duration
            - input_number.pixel_node_display_brightness
            - input_number.pixel_node_display_shakeperiod
      - type: entities
        title: Textzeilen
        show_header_toggle: false
        entities:
            - input_boolean.pixel_node_msg0
            - input_boolean.pixel_node_msg1
            - input_boolean.pixel_node_msg2
            - input_boolean.pixel_node_msg3
            - input_boolean.pixel_node_msg4
            - input_boolean.pixel_node_msg5
            - input_boolean.pixel_node_msg6
            - input_boolean.pixel_node_msg7
            - input_boolean.pixel_node_msg8
            - input_boolean.pixel_node_msg9
            - input_boolean.pixel_node_msg10
            - input_boolean.pixel_node_msg11
            - input_boolean.pixel_node_msg12
            - input_boolean.pixel_node_msg13
            - input_boolean.pixel_node_msg14
            - input_boolean.pixel_node_msg15
            - input_boolean.pixel_node_msg16
            - input_boolean.pixel_node_msg17
            # - input_boolean.pixel_node_msg18
            # - input_boolean.pixel_node_msg19

  - title: Staubsager
    path: vacuum
    panel: false
    cards:
      - type: entities
        title: Saugroboter
        show_header_toggle: false
        entities:
            - input_datetime.vacuum_period_start
            - input_datetime.vacuum_period_end
            - input_boolean.daily_vacuum_done
            - input_boolean.daily_vacuum
            - input_boolean.dustbin_notification
