#
# lovelace configuration - one big file for all
#

title: !env_var HA_TITLE
views:

  - title: Zeiten
    path: lights
    panel: false
    cards:
      - type: entities
        title: Abwesenheit
        show_header_toggle: false
        entities:
            - input_boolean.light_simulation
            - input_number.max_random_off_duration
      - type: entities
        title: Zeiten
        entities:
            - input_datetime.standup_workday
            - input_datetime.standup_weekend
            - input_datetime.sleep
            - input_number.light_timeout
            - input_boolean.light_delay_bath
            - input_boolean.light_delay_shower
      - type: entities
        title: Fernseher aus
        entities:
            - input_number.tvoff_lightsoff_delay1
            - input_number.tvoff_lightsoff_delay2
            - input_datetime.tv_off_period_start
            - input_datetime.tv_off_period_end
      - type: entities
        title: Nachtlicht
        entities:
            - input_number.nightlight_duration
            - input_datetime.nightlight_end
      - type: entities
        title: PiTouch
        entities:
            - input_number.pitouch_delay
            - input_datetime.pitouch_off
            - input_select.pitouch_temp_display
      - type: entities
        title: Lichterkette
        show_header_toggle: false
        entities:
            - input_number.effect_delay
      - type: entities
        title: Zirkulationspumpe Heizung
        show_header_toggle: false
        entities:
            - input_boolean.circulating_pump_activated
            - input_number.circulating_pump_on_period
            - input_number.circulating_pump_on_duration
            - input_number.circulating_pump_activated_after_standup
            - input_number.circulating_pump_activated_before_sleeping
      - type: entities
        title: USV
        show_header_toggle: false
        entities:
            - input_number.ups_shutdown_at_battery_runtime

  - title: Garten
    path: garden
    panel: false
    cards:
      - type: entities
        title: Gartenbewässerung
        show_header_toggle: false
        entities:
            - input_number.irrigation_duration
            - input_boolean.irrigation_activated
            - input_datetime.irrigation_start1
            - input_select.irrigation_day1
            - input_select.irrigation_day2
            - input_select.irrigation_day3
            - input_number.irrigation_rain_threshold
            - input_number.irrigation_no_rain_days_threshold
            - input_number.irrigation_temperature_threshold
            - input_number.irrigation_warm_days_threshold
      - type: entities
        title: Rasenmäher
        show_header_toggle: false
        entities:
            - input_boolean.mowing_activated
            - input_datetime.mowing_start
            - input_datetime.mowing_end
            - input_select.mowing_day1
            - input_select.mowing_day2
            - input_select.mowing_day3
      - type: entities
        title: Bodenfeuchte
        show_header_toggle: false
        entities:
            - input_number.soil_moisture1_min_voltage
            - input_number.soil_moisture1_max_voltage
            - input_number.soil_moisture2_min_voltage
            - input_number.soil_moisture2_max_voltage
            - input_number.soil_moisture3_min_voltage
            - input_number.soil_moisture3_max_voltage
      - type: entities
        title: Pool
        show_header_toggle: false
        entities:
            - input_number.pool_pump_duration
            - input_datetime.pool_pump_start1
            - input_datetime.pool_pump_start2
      - type: markdown
        title: Hinweise
        content: >
            ### Gartenbewässerung

            Die Bewässerung erfolgt an den eingestellten Tagen zur jeweiliegen eingestellten Periode.
            Es werden die regenlosen und die warmen Tage gezählt.
            Ein Tag ist regenlos, wenn der Schwellwert nicht überschritten wird.
            Ein weiterer warmer Tag wird gezählt, wenn der gewählte Schwellwert überschritten wird.
            Kurz vor Mitternacht wird gezählt und ermittelt, ob am nächsten Tag gegossen werden könnte.
            Dazu muss die Anzahl der regenlosen Tage UND die Anzahl der warmen Tage den jeweiligen Schwellwert überschreiten.

            Eine manuelle Steuerung kann erfolgen, wenn die Automatisierungsregel "irrigation_activate_period_1" deaktiviert wird.

            Die Bewässerungsdauer wird in der Regel "irrigation_set_duration" ermittelt.
            Die Standarddauer beträgt 60 min, ab 25°C beträgt sie 90 min und ab 30°C wird für 120 min bewässert.

            ### Pumpdauer

            Der Pool sollte täglich zweimal umgewälzt werden. Somit ergibt sich die tägliche Gesamtpumpdauer von 3,2h (3h und 6min<sup></sup>) aus dem Poolvolumen von 16m<sup>3</sup> und einem Pumpdurchsatz von 10m<sup>3</sup>/h.

  - title: Schalter
    path: buttons
    panel: false
    cards:
      - type: entities
        title: Drücker
        show_header_toggle: true
        entities:
            - input_boolean.button_indoor_activated
            - binary_sensor.button_indoor
            - input_boolean.button_garage_activated
            - binary_sensor.button_garage
            - input_boolean.button_pool_activated
            - binary_sensor.button_pool
            - input_boolean.gesture_kitchen_activated
            - binary_sensor.gesture_kitchen
            - input_boolean.touch_bedroom_activated
            - binary_sensor.ttp223_bedroom_touch1
            - binary_sensor.ttp223_bedroom_touch2
            - binary_sensor.ttp223_bedroom_touch3
            - binary_sensor.ttp223_bedroom_touch4

  - title: Pixel Node
    path: pixelnode
    panel: false
    cards:
      - type: entities
        title: Datum und Zeit
        show_header_toggle: false
        entities:
            - input_boolean.pixel_node_time
            - input_boolean.pixel_node_date
            - input_boolean.pixel_node_weekday
      - type: entities
        title: Anzeige
        show_header_toggle: false
        entities:
            - input_number.pixel_node_display_duration
            - input_number.pixel_node_display_brightness
            - input_number.pixel_node_display_shakeperiod
      - type: entities
        title: Textzeilen
        show_header_toggle: false
        entities:
            - input_boolean.pixel_node_msg0
            - input_boolean.pixel_node_msg1
            - input_boolean.pixel_node_msg2
            - input_boolean.pixel_node_msg3
            - input_boolean.pixel_node_msg4
            - input_boolean.pixel_node_msg5
            - input_boolean.pixel_node_msg6
            - input_boolean.pixel_node_msg7
            - input_boolean.pixel_node_msg8
            - input_boolean.pixel_node_msg9
            - input_boolean.pixel_node_msg10
            - input_boolean.pixel_node_msg11
            - input_boolean.pixel_node_msg12
            - input_boolean.pixel_node_msg13
            - input_boolean.pixel_node_msg14
            - input_boolean.pixel_node_msg15
            - input_boolean.pixel_node_msg16
            - input_boolean.pixel_node_msg17
            - input_boolean.pixel_node_msg18
            # - input_boolean.pixel_node_msg19

  - title: Staubsager
    path: vacuum
    panel: false
    cards:
      - type: entities
        title: Saugroboter
        show_header_toggle: false
        entities:
            - input_datetime.vacuum_period_start
            - input_datetime.vacuum_period_end
            - input_boolean.daily_vacuum_done
            - input_boolean.daily_vacuum
            - input_boolean.dustbin_notification

  - title: Energie
    path: energy
    panel: false
    cards:
      - type: entities
        title: Elektrozähler
        show_header_toggle: false
        entities:
            - input_number.electricity_meter_threshold_power
      - type: entities
        title: Preise
        show_header_toggle: false
        entities:
            - input_number.electricity_price_in
            - input_number.electricity_price_out

  - title: Fensterrollos
    path: shutter
    panel: false
    cards:
      - type: entities
        title: Parameter
        show_header_toggle: false
        entities:
            - input_boolean.cover_closing_at_cold_activated
            - input_number.rooflight_close_below_temp
      - type: entities
        title: Auswahl
        show_header_toggle: false
        entities:
            - input_boolean.cover_bedroom
            - input_boolean.cover_bath
            - input_boolean.cover_office
            - input_boolean.cover_nursery
