#
# lovelace configuration - one big file for all
#

title: !env_var HA_TITLE
views:

  - title: Sensorwerte
    path: values
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.dht22_lounge_pressure
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.ds18b20_pool_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: markdown
                content: <br/><br/><br/><br/><br/><br/><br/><br/>
              - type: sensor
                entity: sensor.rain_garden_precipitation_last7d
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.rain_garden_precipitation_last24h
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.rain_garden_precipitation
                graph: line
                detail: 2
                hours_to_show: 24
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.dht22_lounge_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.dht22_terrace_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.dht22_roof_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.relay_garage_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.dht22_office_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.dht11_utilityroom_temperature
                graph: line
                detail: 2
                hours_to_show: 24
          - type: horizontal-stack
            cards:
              - type: sensor
                icon: mdi:show_chart
                entity: sensor.dht22_lounge_humidity
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.dht22_terrace_humidity
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.dht22_roof_humidity
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.relay_garage_humidity
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.dht22_office_humidity
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.dht11_utilityroom_humidity
                graph: line
                detail: 2
                hours_to_show: 24
          - type: horizontal-stack
            cards:
              - type: sensor
                icon: mdi:show_chart
                entity: sensor.dht22_lounge_tau
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.dht22_terrace_tau
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.dht22_roof_tau
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.relay_garage_tau
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.dht22_office_tau
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.dht11_utilityroom_tau
                graph: line
                detail: 2
                hours_to_show: 24
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.soil_garden_temperature1
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.soil_garden_temperature2
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.soil_garden_temperature3
                graph: line
                detail: 2
                hours_to_show: 24
              - type: markdown
                content: <br/><br/><br/><br/><br/><br/><br/><br/>
              - type: markdown
                content: <br/><br/><br/><br/><br/><br/><br/><br/>
              - type: markdown
                content: <br/><br/><br/><br/><br/><br/><br/><br/>
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.soil_garden_moisture1
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.soil_garden_moisture2
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.soil_garden_moisture3
                graph: line
                detail: 2
                hours_to_show: 24
              - type: markdown
                content: <br/><br/><br/><br/><br/><br/><br/><br/>
              - type: markdown
                content: <br/><br/><br/><br/><br/><br/><br/><br/>
              - type: markdown
                content: <br/><br/><br/><br/><br/><br/><br/><br/>

  - title: Pflanzen
    path: plants
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.goldfruchtpalme_flowercare_moisture
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
              - type: sensor
                entity: sensor.goldfruchtpalme_flowercare_conductivity
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.goldfruchtpalme_flowercare_brightness
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.goldfruchtpalme_flowercare_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.goldfruchtpalme_flowercare_battery
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.birkenfeige_flowercare_moisture
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
              - type: sensor
                entity: sensor.birkenfeige_flowercare_conductivity
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.birkenfeige_flowercare_brightness
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.birkenfeige_flowercare_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.birkenfeige_flowercare_battery
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.palmlilie_flowercare_moisture
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
              - type: sensor
                entity: sensor.palmlilie_flowercare_conductivity
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.palmlilie_flowercare_brightness
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.palmlilie_flowercare_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.palmlilie_flowercare_battery
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.bogenhanf_flowercare_moisture
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
              - type: sensor
                entity: sensor.bogenhanf_flowercare_conductivity
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.bogenhanf_flowercare_brightness
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.bogenhanf_flowercare_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.bogenhanf_flowercare_battery
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.korbmarante_flowercare_moisture
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
              - type: sensor
                entity: sensor.korbmarante_flowercare_conductivity
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.korbmarante_flowercare_brightness
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.korbmarante_flowercare_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.korbmarante_flowercare_battery
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.fensterblatt_flowercare_moisture
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
              - type: sensor
                entity: sensor.fensterblatt_flowercare_conductivity
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.fensterblatt_flowercare_brightness
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.fensterblatt_flowercare_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.fensterblatt_flowercare_battery
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.gummibaum_flowercare_moisture
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
              - type: sensor
                entity: sensor.gummibaum_flowercare_conductivity
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.gummibaum_flowercare_brightness
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.gummibaum_flowercare_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.gummibaum_flowercare_battery
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.fiederaralie_flowercare_moisture
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
              - type: sensor
                entity: sensor.fiederaralie_flowercare_conductivity
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.fiederaralie_flowercare_brightness
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.fiederaralie_flowercare_temperature
                graph: line
                detail: 2
                hours_to_show: 24
              - type: sensor
                entity: sensor.fiederaralie_flowercare_battery
                graph: line
                detail: 2
                hours_to_show: 24
                limits:
                  min: 0
                  max: 100
