# Becker services

pair:
  description: "Pair with a cover receiver, when master transmitter is in pairing mode"
  fields:
    channel:
      description: "Channel to pair the receiver on (1-7)"
      example: 1
    unit:
      description: "Sender unit to use for pairing (1-5)"
      example: 1
log_units:
  description: "Log all configured/paired units"
