###
### automation.yaml
###
### 04.11.2016 split up
###

#------------------------------------------------------------------------------------
# outdoor lights at night
  - alias: outer_lights_on_at_night
    hide_entity: False
    trigger:
      - platform: sun
        event: sunset
        offset: "00:00:00"
    action:
        service: light.turn_on
        entity_id:
            - group.automatic_night_lights

  - alias: outer_lights_off_at_morning
    hide_entity: False
    trigger:
      - platform: sun
        event: sunrise
        offset: "+00:00:00"
    action:
        service: light.turn_off
        entity_id:
            - group.automatic_night_lights

#------------------------------------------------------------------------------------
# terrarium lights
  - alias: terrarium_lights_on
    hide_entity: False
    trigger:
      - platform: sun
        event: sunrise
        offset: "+00:00:00"
    action:
        service: light.turn_on
        entity_id:
            - light.sonofflocation2_socket

  - alias: terrarium_lights_off
    hide_entity: False
    trigger:
      - platform: sun
        event: sunset
        offset: "00:00:00"
    action:
        service: light.turn_off
        entity_id:
            - light.sonofflocation2_socket

#------------------------------------------------------------------------------------
# heater pump
  - alias: heater_circulating_pump_on
    hide_entity: False
    trigger:                    # any event
      - platform: time
        at: '05:00:00'
      - platform: time
        at: '05:30:00'
      - platform: time
        at: '08:00:00'
      - platform: state
        entity_id: group.family_devices
        to: 'home'
      - platform: state
        entity_id: input_boolean.manual_holiday_indicator
        # any state
    condition:                  # all conditions
      - condition: and
        conditions:
          - condition: state
            entity_id: group.family_devices
            state: 'home'
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.manual_holiday_indicator
                    state: 'on'
                  - condition: time         # any day
                    after: '08:00:00'
                    before: '22:00:00'
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.manual_holiday_indicator
                    state: 'off'
                  - condition: or
                    conditions:
                      - condition: time
                        after: '05:00:00'
                        before: '22:00:00'
                        weekday:
                          - mon
                      - condition: time
                        after: '05:30:00'
                        before: '22:00:00'
                        weekday:
                          - tue
                          - wed
                          - thu
                          - fri
                      - condition: time
                        after: '08:00:00'
                        before: '22:00:00'
                        weekday:
                          - sat
                          - sun
    action:
        service: switch.turn_on
        entity_id:
            - switch.sonoffutilityroom_pump

  - alias: heater_circulating_pump_off
    hide_entity: False
    trigger:                    # any event, no condition necessary
      - platform: time
        at: '22:00:00'
      - platform: state
        entity_id: group.family_devices
        to: 'not_home'
      - platform: state
        entity_id: input_boolean.manual_holiday_indicator
        # any state
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.manual_holiday_indicator
            state: 'off'
          - condition: state
            entity_id: group.family_devices
            state: 'not_home'
          - condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.manual_holiday_indicator
                state: 'on'
              - condition: time
                before: '08:00:00'
                after: '22:00:00'
    action:
        service: switch.turn_off
        entity_id:
            - switch.sonoffutilityroom_pump

#------------------------------------------------------------------------------------
# daily lights
  - alias: lights_on_at_coming_home_or_sunset
    hide_entity: False
    trigger:
      - platform: state
        entity_id: group.family_devices
        to: 'home'
      - platform: sun
        event: sunset
        offset: "00:00:00"
    condition:
      - condition: sun
        after: sunset
        after_offset: "00:00:00"
      - condition: time
        before: '22:00:00'
      - condition: state
        entity_id: group.family_devices
        state: 'home'
    action:
        service: homeassistant.turn_on
        entity_id: 
            - group.daily_lights
            - light.sonofflocation3_lamp

  - alias: lights_off_at_getting_out_or_sunrise
    hide_entity: False
    trigger:
      - platform: state
        entity_id: group.family_devices
        to: 'not_home'
      - platform: sun
        event: sunrise
        offset: "+00:00:00"
    action:
        service: homeassistant.turn_off
        entity_id: 
            - group.daily_lights
            - light.sonofflocation3_lamp

  - alias: lights_off_at_tv_switched_off
    hide_entity: False
    trigger:
        platform: state
        entity_id: media_player.sony_bravia_tv
        from: "on"
        to: "off"
    condition:
      - condition: time
        after: '21:00:00'
        before: '06:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id: 
            - group.daily_lights
      - delay: 00:07:00
      - service: homeassistant.turn_off
        entity_id: 
            - light.sonofflocation3_lamp

#------------------------------------------------------------------------------------
# buttons

  - alias: button_no1
    hide_entity: false
    trigger:
      - platform: state
        entity_id: binary_sensor.buttonno1
        to: 'on'
    action:
      - service: light.toggle
        entity_id: light.xmastreedining_leds

  # - alias: button_no2_garage
    # hide_entity: false
    # trigger:
      # - platform: state
        # entity_id: binary_sensor.buttongarage
        # to: 'on'
    # action:
      # - service: light.toggle
        # # entity_id: light.relay2dining_lamp
        # entity_id: light.rfhubfirst_lampStudyPillar


  - alias: button_no3
    hide_entity: false
    trigger:
      - platform: state
        entity_id: binary_sensor.buttonno3
        to: '_on'
    action:
      - service: light.toggle
        entity_id: light.xmastreedining_leds

  - alias: open_garage_door
    hide_entity: false
    trigger:
      - platform: state
        entity_id: binary_sensor.buttongarage
        to: 'on'
    condition:
      - condition: state
        entity_id: cover.relaygarage
        state: 'closed'
    action:
      - service: cover.open_cover
        entity_id: cover.relaygarage

  - alias: close_garage_door
    hide_entity: false
    trigger:
      - platform: state
        entity_id: binary_sensor.buttongarage
        to: 'on'
    condition:
      - condition: state
        entity_id: cover.relaygarage
        state: 'open'
    action:
      - service: cover.close_cover
        entity_id: cover.relaygarage

#------------------------------------------------------------------------------------
# pixel node

  - alias: pixel_node_preferences
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_boolean.pixel_node_time
      - platform: state
        entity_id: input_boolean.pixel_node_date
      - platform: state
        entity_id: input_boolean.pixel_node_weekday
      - platform: state
        entity_id: input_slider.pixel_node_display_duration
      - platform: state
        entity_id: input_slider.pixel_node_display_brightness
      - platform: state
        entity_id: input_boolean.pixel_node_msg0
      - platform: state
        entity_id: input_boolean.pixel_node_msg1
      - platform: state
        entity_id: input_boolean.pixel_node_msg2
      - platform: state
        entity_id: input_boolean.pixel_node_msg3
      - platform: state
        entity_id: input_boolean.pixel_node_msg4
      - platform: state
        entity_id: input_boolean.pixel_node_msg5
      - platform: state
        entity_id: input_boolean.pixel_node_msg6
      - platform: state
        entity_id: input_boolean.pixel_node_msg7
      - platform: state
        entity_id: input_boolean.pixel_node_msg8
      - platform: state
        entity_id: input_boolean.pixel_node_msg9
      - platform: state
        entity_id: input_boolean.pixel_node_msg10
      - platform: state
        entity_id: input_boolean.pixel_node_msg11
      - platform: state
        entity_id: input_boolean.pixel_node_msg12
      - platform: state
        entity_id: input_boolean.pixel_node_msg13
      - platform: state
        entity_id: input_boolean.pixel_node_msg14
      - platform: state
        entity_id: input_boolean.pixel_node_msg15
      - platform: state
        entity_id: input_boolean.pixel_node_msg16
      - platform: state
        entity_id: input_boolean.pixel_node_msg17
      - platform: state
        entity_id: input_boolean.pixel_node_msg18
      - platform: state
        entity_id: input_boolean.pixel_node_msg19
    action:
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/pixel/kitchen/command
            payload: >
                {
                    "display": {
                        "duration": {{ states ( 'input_slider.pixel_node_display_duration' ) | round ( 0 ) }},
                        "brightness": {{ states ( 'input_slider.pixel_node_display_brightness' ) | round ( 0 ) }},
                        "time": "{{ states ( 'input_boolean.pixel_node_time' ) }}",
                        "date": "{{ states ( 'input_boolean.pixel_node_date' ) }}",
                        "weekday": "{{ states ( 'input_boolean.pixel_node_weekday' ) }}",
                        "enabled": [
                            "{{ states ( 'input_boolean.pixel_node_msg0' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg1' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg2' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg3' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg4' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg5' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg6' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg7' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg8' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg9' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg10' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg11' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg12' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg13' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg14' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg15' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg16' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg17' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg18' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg19' ) }}"
                        ]
                    }
                }
            qos: 0
            retain: true

#------------------------------------------------------------------------------------
# display

  - alias: display_show_outdoor_temperature
    hide_entity: false
    trigger:
      - platform: mqtt
        topic: nodes@home/sensor/DHT11/terrace/value/temperature
    action:
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/pixel/kitchen/message/temperature/outdoor
            payload: >
                {
                    "messages": [
                        {
                            "line": 0,
                            "text": " Außen: {{ trigger.payload_json.value }}°C"
                        }
                    ]
                }
            qos: 0
            retain: true
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/oled/kitchen/message/outdoor
            payload: >
                { "title": "Terasse", "text": "{{trigger.payload_json.value}}°C" }
            qos: 0
            retain: true

  - alias: display_show_indoor_temperature
    hide_entity: false
    trigger:
      - platform: mqtt
        topic: nodes@home/sensor/DHT11/lounge/value/temperature
    action:
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/pixel/kitchen/message/temperature/indoor
            payload: >
                {
                    "messages": [
                        {
                            "line": 1,
                            "text": " Innen: {{ trigger.payload_json.value }}°C"
                        }
                    ]
                }
            qos: 0
            retain: true
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/oled/kitchen/message/indoor
            payload: >
                { "title": "Wohnzimmer", "text": "{{trigger.payload_json.value}}°C" }
            qos: 0
            retain: true

  - alias: display_show_pool_temperature
    hide_entity: false
    trigger:
      - platform: mqtt
        topic: nodes@home/sensor/ds18b20/pool/value/temperature
    action:
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/pixel/kitchen/message/temperature/pool
            payload: >
                {
                    "messages": [
                        {
                            "line": 12,
                            "text": " Pool: {{ trigger.payload_json.value | round ( 1 ) }}°C"
                        }
                    ]
                }
            qos: 0
            retain: true
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/oled/kitchen/message/pool
            payload: >
                { "title": "Pool", "text": "{{trigger.payload_json.value | round ( 1 )}}°C" }
            qos: 0
            retain: true

#------------------------------------------------------------------------------------
  # - alias: AnAus
    # hide_entity: False
    # trigger:
        # platform: time
        # seconds: '/20'
    # action:
        # service: light.toggle
        # # entity_id: group.rooms_terrace, group.rooms_backyard
        # entity_id: group.rooms_backyard, group.rooms_terrace
