###
### automation.yaml
###
### 04.11.2016 split up
###

#------------------------------------------------------------------------------------
# outdoor lights at night
  - alias: outdoor_lights_on_at_night
    hide_entity: False
    trigger:
      - platform: sun
        event: sunset
        offset: "00:00:00"
    action:
      - service: light.turn_on
        entity_id:
            - group.automatic_outdoor_lights

  - alias: outdoor_lights_off_at_morning
    hide_entity: False
    trigger:
      - platform: sun
        event: sunrise
        offset: "+00:00:00"
    action:
      - service: light.turn_off
        entity_id:
            - group.automatic_outdoor_lights

#------------------------------------------------------------------------------------
# heater pump
  - alias: heater_circulating_pump_on
    hide_entity: False
    trigger:                    # any event
      - platform: time
        at: '05:30:00'
      - platform: time
        at: '08:00:00'
      - platform: state
        entity_id: group.family_devices
        to: 'home'
    condition:                  # all conditions
      - condition: and
        conditions:
          - condition: state
            entity_id: group.family_devices
            state: 'home'
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: binary_sensor.workday_sensor
                    state: 'on'
                  - condition: time
                    after: '05:30:00'
                    before: '22:00:00'
              - condition: and
                conditions:
                  - condition: state
                    entity_id: binary_sensor.workday_sensor
                    state: 'off'
                  - condition: time
                    after: '08:00:00'
                    before: '22:00:00'
    action:
      - service: switch.turn_on
        entity_id:
            - switch.sonoffutilityroom_pump

  - alias: heater_circulating_pump_off
    hide_entity: False
    trigger:                    # any event, no condition necessary
      - platform: time
        at: '22:00:00'
      - platform: state
        entity_id: group.family_devices
        to: 'not_home'
    action:
      - service: switch.turn_off
        entity_id:
            - switch.sonoffutilityroom_pump

#------------------------------------------------------------------------------------
# indoor lights
  - alias: indoor_lights_on_at_coming_home_or_sunset
    hide_entity: False
    trigger:
      - platform: state
        entity_id: group.family_devices
        to: 'home'
      - platform: sun
        event: sunset
        offset: "00:00:00"
    condition:
      - condition: sun
        after: sunset
        after_offset: "00:00:00"
      - condition: time
        before: '22:00:00'
      - condition: or
        conditions:
          - condition: state
            entity_id: group.family_devices
            state: 'home'
          - condition: state
            entity_id: input_boolean.light_simulation
            state: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: 
            - group.automatic_indoor_lights

  - alias: indoor_lights_by_night_on_at_coming_home
    hide_entity: False
    trigger:
      - platform: state
        entity_id: group.family_devices
        to: 'home'
    condition:
      - condition: sun
        after: sunset
        after_offset: "00:00:00"
      - condition: time
        after: '22:00:00'
        before: '04:00:00'
      - condition: state
        entity_id: group.family_devices
        state: 'home'
    action:
      - service: homeassistant.turn_on
        entity_id: 
            - group.automatic_indoor_lights_by_night
      - delay: 00:15:00
      - service: homeassistant.turn_off
        entity_id: 
            - group.automatic_indoor_lights_by_night

  - alias: indoor_lights_off_at_getting_out_or_sunrise
    hide_entity: False
    trigger:
      - platform: state
        entity_id: group.family_devices
        to: 'not_home'
      - platform: sun
        event: sunrise
        offset: "+00:00:00"
    action:
      - service: scene.turn_on
        entity_id: scene.kitchen_background_light
      - service: homeassistant.turn_off
        entity_id: 
            - group.automatic_indoor_lights
            - group.automatic_indoor_lights_immediatly_switched_off_extra

  - alias: indoor_lights_off_when_tv_switched_off
    hide_entity: False
    trigger:
        platform: state
        entity_id: media_player.sony_bravia_tv
        from: "on"
        to: "off"
        for:
            minutes: 1
    condition:
      - condition: time
        after: '21:00:00'
        before: '06:00:00'
    action:
      - service: scene.turn_on
        entity_id: scene.kitchen_background_light
      - service: homeassistant.turn_off
        entity_id: 
            - group.automatic_indoor_lights_immediatly_switched
            - group.automatic_indoor_lights_immediatly_switched_off_extra
      - delay: 00:07:00
      - service: homeassistant.turn_off
        entity_id: 
            - group.automatic_indoor_lights_delayed_switched

  - alias: indoor_lights_off_after_random_delay
    hide_entity: False
    trigger:
      - platform: time
        at: '22:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.light_simulation
        state: 'on'
    action:
      # switch off between 22:00 amd 24:00
      - delay: '{{ ( range ( 0, 2 ) | random | int ) }}:{{ ( range ( 0, 60 ) | random | int ) }}:00'
      - service: scene.turn_on
        entity_id: scene.kitchen_background_light
      - service: homeassistant.turn_off
        entity_id: 
            - group.automatic_indoor_lights
            - group.automatic_indoor_lights_immediatly_switched_off_extra

#------------------------------------------------------------------------------------
# buttons

  - alias: indoor_lights_on_by_button
    hide_entity: false
    trigger:
      - platform: state
        entity_id: binary_sensor.buttonindoor
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.button_indoor_activated
        state: 'on'
      # indicator for indoor night lights
      - condition: state
        entity_id: light.relaydining1_lamp
        state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: 
            - group.automatic_indoor_lights
        
  - alias: indoor_lights_off_by_button
    hide_entity: false
    trigger:
      - platform: state
        entity_id: binary_sensor.buttonindoor
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.button_indoor_activated
        state: 'on'
      # indicator for indoor night lights
      - condition: state
        entity_id: light.relaydining1_lamp
        state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: 
            - group.automatic_indoor_lights

  - alias: open_garage_door
    hide_entity: false
    trigger:
      - platform: state
        entity_id: binary_sensor.buttongarage
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.button_garage_activated
        state: 'on'
      - condition: state
        entity_id: cover.relaygarage
        state: 'closed'
    action:
      - service: cover.open_cover
        entity_id: cover.relaygarage

  - alias: close_garage_door
    hide_entity: false
    trigger:
      - platform: state
        entity_id: binary_sensor.buttongarage
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.button_garage_activated
        state: 'on'
      - condition: state
        entity_id: cover.relaygarage
        state: 'open'
    action:
      - service: cover.close_cover
        entity_id: cover.relaygarage

#------------------------------------------------------------------------------------
# kitchen led
  - alias: kitchen_desk_light_on
    hide_entity: false
    trigger:
      - platform: state
        entity_id: binary_sensor.gesturekitchen
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.gesture_kitchen_activated
        state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: light.sonoffkitchen_led
            state: 'off'
          - condition: and
            conditions:
              - condition: state
                entity_id: light.sonoffkitchen_led
                state: 'on'
              - condition: template
                value_template: '{{ states.light.sonoffkitchen_led.attributes.color_temp == 500 }}'
    action:
      - service: scene.turn_on
        entity_id: scene.kitchen_full_light

  - alias: kitchen_desk_light_off
    hide_entity: false
    trigger:
      - platform: state
        entity_id: binary_sensor.gesturekitchen
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.gesture_kitchen_activated
        state: 'on'
      - condition: state
        entity_id: light.sonoffkitchen_led
        state: 'on'
      # indicator for indoor night lights
      - condition: state
        entity_id: light.relaydining1_lamp
        state: 'off'
    action:
      - service: scene.turn_on
        entity_id: scene.kitchen_background_light
      - service: light.turn_off
        entity_id: light.sonoffkitchen_led

  - alias: kitchen_desk_light_off_at_night
    hide_entity: false
    trigger:
      - platform: state
        entity_id: binary_sensor.gesturekitchen
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.gesture_kitchen_activated
        state: 'on'
      # indicator for indoor night lights
      - condition: state
        entity_id: light.relaydining1_lamp
        state: 'on'
      - condition: and
        conditions:
          - condition: state
            entity_id: light.sonoffkitchen_led
            state: 'on'
          - condition: template
            value_template: '{{ states.light.sonoffkitchen_led.attributes.color_temp != 500 }}'
    action:
      - service: scene.turn_on
        entity_id: scene.kitchen_background_light

#------------------------------------------------------------------------------------
# pool

  - alias: pool_pump_on_off
    hide_entity: False
    trigger:
      - platform: time
        at: '11:00:00'
      - platform: time
        at: '20:00:00'
    action:
      - service: switch.turn_on
        entity_id:
            - switch.sonoffpool_socket
      - delay: 02:00:00
      - service: switch.turn_off
        entity_id:
            - switch.sonoffpool_socket

  - alias: button_pool
    hide_entity: false
    trigger:
      - platform: state
        entity_id: binary_sensor.buttonpool
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.button_pool_activated
        state: 'on'
    action:
      - service: switch.toggle
        entity_id: switch.sonoffpool_socket
        
#------------------------------------------------------------------------------------
# pixel node

  - alias: pixel_node_preferences
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_boolean.pixel_node_time
      - platform: state
        entity_id: input_boolean.pixel_node_date
      - platform: state
        entity_id: input_boolean.pixel_node_weekday
      - platform: state
        entity_id: input_slider.pixel_node_display_duration
      - platform: state
        entity_id: input_slider.pixel_node_display_brightness
      - platform: state
        entity_id: input_boolean.pixel_node_msg0
      - platform: state
        entity_id: input_boolean.pixel_node_msg1
      - platform: state
        entity_id: input_boolean.pixel_node_msg2
      - platform: state
        entity_id: input_boolean.pixel_node_msg3
      - platform: state
        entity_id: input_boolean.pixel_node_msg4
      - platform: state
        entity_id: input_boolean.pixel_node_msg5
      - platform: state
        entity_id: input_boolean.pixel_node_msg6
      - platform: state
        entity_id: input_boolean.pixel_node_msg7
      - platform: state
        entity_id: input_boolean.pixel_node_msg8
      - platform: state
        entity_id: input_boolean.pixel_node_msg9
      - platform: state
        entity_id: input_boolean.pixel_node_msg10
      - platform: state
        entity_id: input_boolean.pixel_node_msg11
      - platform: state
        entity_id: input_boolean.pixel_node_msg12
      - platform: state
        entity_id: input_boolean.pixel_node_msg13
      - platform: state
        entity_id: input_boolean.pixel_node_msg14
      - platform: state
        entity_id: input_boolean.pixel_node_msg15
      - platform: state
        entity_id: input_boolean.pixel_node_msg16
      - platform: state
        entity_id: input_boolean.pixel_node_msg17
      - platform: state
        entity_id: input_boolean.pixel_node_msg18
      - platform: state
        entity_id: input_boolean.pixel_node_msg19
    action:
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/pixel/kitchen/command
            payload: >
                {
                    "display": {
                        "duration": {{ states ( 'input_slider.pixel_node_display_duration' ) | round ( 0 ) }},
                        "brightness": {{ states ( 'input_slider.pixel_node_display_brightness' ) | round ( 0 ) }},
                        "time": "{{ states ( 'input_boolean.pixel_node_time' ) }}",
                        "date": "{{ states ( 'input_boolean.pixel_node_date' ) }}",
                        "weekday": "{{ states ( 'input_boolean.pixel_node_weekday' ) }}",
                        "enabled": [
                            "{{ states ( 'input_boolean.pixel_node_msg0' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg1' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg2' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg3' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg4' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg5' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg6' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg7' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg8' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg9' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg10' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg11' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg12' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg13' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg14' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg15' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg16' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg17' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg18' ) }}",
                            "{{ states ( 'input_boolean.pixel_node_msg19' ) }}"
                        ]
                    }
                }
            qos: 0
            retain: true

#------------------------------------------------------------------------------------
# display

  - alias: display_show_outdoor_temperature
    hide_entity: false
    trigger:
      - platform: mqtt
        topic: nodes@home/sensor/DHT22/terrace/value/temperature
    action:
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/pixel/kitchen/message/temperature/outdoor
            payload: >
                {
                    "messages": [
                        {
                            "line": 0,
                            "text": " Außen: {{ trigger.payload_json.value }}°C"
                        }
                    ]
                }
            qos: 0
            retain: true
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/oled/kitchen/message/outdoor
            payload: >
                { "title": "Terasse", "text": "{{trigger.payload_json.value}}°C" }
            qos: 0
            retain: true

  - alias: display_show_indoor_temperature
    hide_entity: false
    trigger:
      - platform: mqtt
        topic: nodes@home/sensor/DHT22/lounge/value/temperature
    action:
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/pixel/kitchen/message/temperature/indoor
            payload: >
                {
                    "messages": [
                        {
                            "line": 1,
                            "text": " Innen: {{ trigger.payload_json.value }}°C"
                        }
                    ]
                }
            qos: 0
            retain: true
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/oled/kitchen/message/indoor
            payload: >
                { "title": "Wohnzimmer", "text": "{{trigger.payload_json.value}}°C" }
            qos: 0
            retain: true

  - alias: display_show_pool_temperature
    hide_entity: false
    trigger:
      - platform: mqtt
        topic: nodes@home/sensor/ds18b20/pool/value/temperature
    action:
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/pixel/kitchen/message/temperature/pool
            payload: >
                {
                    "messages": [
                        {
                            "line": 12,
                            "text": " Pool: {{ trigger.payload_json.value | round ( 1 ) }}°C"
                        }
                    ]
                }
            qos: 0
            retain: true
      - service: mqtt.publish
        data_template:
            topic: nodes@home/display/oled/kitchen/message/pool
            payload: >
                { "title": "Pool", "text": "{{trigger.payload_json.value | round ( 1 )}}°C" }
            qos: 0
            retain: true

#------------------------------------------------------------------------------------
